# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
        # run the ruff linter
    -   id: ruff-check
        args: [--fix]
        files: ^backend/
        # run the ruff formatter
    -   id: ruff-format
        types_or: [ python, pyi ]
        files: ^backend/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
        exclude: .devcontainer/devcontainer.json
-   repo: local
    hooks:
    -   id: frontend-format
        name: frontend format
        entry: npm run format
        language: system
        types: [text]
        files: ^frontend/


